modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]]
modId="playdate"
version="${file.jarVersion}"
displayName="Playdate"
logoFile="icon.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description="desc"

[[dependencies.playdate]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playdate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
